Engine ini
adaltas/node-nikita pull request #190
Opened 2020-12-07 19:25 UTC by sergkudinov

There was a issue in `packages/tools/src/repo.coffee.md` on line 113. It is using `ini.parse_multi_brackets`, but when I was moving to consistence `utils` I didn't notice that it is imported from `file.utils`.

2020-12-07 20:21 UTC, wdavidw commented
If tools require files, then why involving the engine package ?

2020-12-09 11:14 UTC, sergkudinov commented
@wdavidw It doesn't require @file. It requires `ini` utilities that were placed in `file` package and originaly in `core`. Since 2 packages (`file` and `tools`) are using same utilites, I decided to move it under `engine`.

2020-12-09 14:25 UTC, wdavidw commented
Engine is not a trash bag ;)

2020-12-09 17:07 UTC, sergkudinov commented
done

2020-12-09 19:47 UTC, wdavidw requested changes

2020-12-09 19:47 UTC, wdavidw commented on packages/tools/src/repo.coffee.md
> +    utils = require "@nikitajs/file/lib/utils"
`tools/package.json` doesn't declare `@nikitajs/file` as a dependency ?

2020-12-10 13:14 UTC, wdavidw approved these changes

2020-12-10 14:07 UTC, merged