docs: update tutorial
adaltas/node-nikita pull request #256
Opened 2021-01-22 17:16 UTC by sergkudinov

It is not meant to be merged as is. It requires a few updates such as for "Scheduling actions" section and improving consistency and correcting the samples.

2021-01-25 11:52 UTC, wdavidw requested changes

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +Nikita is build as a library, which provides simple functions on a host (server, desktop, machine, vm...) either locally or remotely over SSH.
Nikita is a toolkit to automate the execution of your workflows. Use one of the many available actions or create your own functions to build simple to complex deployment pipelines and infrastructures. Actions are transparently executed locally or remotely over SSH from any host.

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +Nikita is written in JavaScript and executed by NodeJs. It is delivered as a Node.js package and is available on [NPM](https://www.npmjs.com/package/nikita).
with Node.js

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +Nikita is written in JavaScript and executed by NodeJs. It is delivered as a Node.js package and is available on [NPM](https://www.npmjs.com/package/nikita).
It is available on NPM

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +It can serve multiple purposes. For example, it can be used in a website with a Node.js backend, where you want to execute actions (writing files, copy, move, executing custom scripts...) or you can
It serves

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +Nikita targets Unix-like system including Linux and macOS. Windows is not supported as a targeting node where to execute actions. It is however known to work as a Nikita host. This mean you can run N
`as long as ` => `and target`

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +Throughout this tutorial, it is assumed you work on Linux or macOS. To be able to run the same code examples without modifications on Windows, the easiest way would be to work inside a [Node.js Docke
Throughout this tutorial, it is assumed you work on Linux or macOS. To be able to run the same code examples without modifications on Windows, you can download a Virtual Machine or use Docker.

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +Throughout this tutorial, it is assumed you work on Linux or macOS. To be able to run the same code examples without modifications on Windows, the easiest way would be to work inside a [Node.js Docke
At the end of the tutorial, you will learn how to use Nikita over SSH. This way, your windows host is used to create your workflow and you can target a remote hosts like a server, a virtual machine or a container.

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +# Change URL to your remote repository URL
Change the URL with your...

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +As you can see, config is made available as the first argument of the handler.
the handler receive one argument, the action. config is a destructure property of action

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +All Nikita actions return [Javascript Promise](https://nodejs.dev/learn/understanding-javascript-promises). To execute your commands sequentially after calling a Nikita action, you have to call an an
All Nikita actions return => A Nikita action always return a JavaScript Promise

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +All Nikita actions return [Javascript Promise](https://nodejs.dev/learn/understanding-javascript-promises). To execute your commands sequentially after calling a Nikita action, you have to call an an
Nikita also provides you the garanty that your action are executed sequentially.

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +You can create a chain of actions that will be executed one after another.
remove this

2021-01-25 11:52 UTC, wdavidw commented on docs/content/about/tutorial.md
> +In order to reuse our new `touch` action, we could isolate it into a separate file. The new file is called a module in Node.js terminology. Nikita `call` will accept the exported object or function.
Move back `A string is interpreted as the module path and will be automatically imported.`

2021-01-26 15:33 UTC, wdavidw requested changes
I don't see my previous comment to be resolved

2021-01-26 15:35 UTC, sergkudinov commented on docs/content/about/tutorial.md
> -At the end of the tutorial, we will show you how a code would look if written in CoffeeScript.
Because we will add a support of coffeescript for every sample.
The second reason, it is not provided in the current tutorial.

2021-01-26 16:19 UTC, sergkudinov commented
> I don't see my previous comment to be resolved

I didn't finish

2021-01-26 17:20 UTC, sergkudinov commented
ready for a review

2021-01-27 08:19 UTC, wdavidw approved these changes

2021-01-27 08:19 UTC, merged