docs: change prismjs theme
adaltas/node-nikita pull request #374
Opened 2021-06-09 12:23 UTC by sergkudinov

2021-06-09 19:51 UTC, wdavidw commented on docs/website/src/components/shared/Content.js
> +      '& .token.operator, .token.entity, .token.url, .language-css .token.string, .style .token.string': {
Please leave a comment explaining why

2021-06-09 19:51 UTC, wdavidw commented on docs/website/src/pages/index.js
> +    '& .token.operator, .token.entity, .token.url, .language-css .token.string, .style .token.string': {
same, add a comment

2021-06-09 19:52 UTC, wdavidw requested changes
Please add comments

2021-06-14 12:42 UTC, sergkudinov commented
> Please add comments

done

2021-06-23 12:10 UTC, merged